apiVersion: v1
data:
  password: "" #cGFzc3dvcmQxMjM= #password123
  username: "" #YWRtaW51c2Vy #adminuser
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds
  namespace: reserved-word-for-namespace-123456789
