apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: reserved-word-for-namespace-123456789
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
