apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: reserved-word-for-namespace-123456789
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
